### PR TITLE
Rename and add release action to deploy action

### PR DESCRIPTION
**Pull request by svenfeld**
This PR adds a release action to the deploy action.
- Creates a tag by using the version which is specified in the pom.xml.
- Adds jars for CA and CA Android to the release.
- Body of release contains the body of merged PRs to previous tag.

### CODE REVIEW

**Review by swissiety — COMMENTED** [review]
how about squashing/merging the commits into master as well automatically?

**Comment by svenfeld** [comment]
What do you mean by that? Is that not done by merging a PR?

**Comment by schlichtig** [comment]
@swissiety This action only works on the master and we use it once everything we want to release has been merged. 
I do not see a need the automate merging (all) PRs from develop as this might take away control of what we want to release and what not.
What is your take?

**Comment by swissiety** [comment]
Oh I assumed we would take the current develop state (or another branch we select to run the workflow on) to deploy and could automate merging that commit into master as well. Downside: deploying older Versions would be harder or needs to be handled by the workflow as well (don't merge then?)

**Comment by schlichtig** [comment]
@swissiety I think that could be a cool feature, but I would like to have this in a seperate action.

So, is this good to merge now?

**Pull request merged**
