### PR TITLE
Fix develop branch

### LINKED ISSUE #240: The build of develop branch is failing on Jenkins
The build of develop branch on Jenkins is failing. The reason is due to an OutOfMemoryError thrown by Maven. This means that the JVM (Jenkins) that is running the project has run out of memory. Currently, a max 8GB of memory is reserved for CryptoAnalysis. After increasing the max memory to 16GB, the error is still persisting. Moreover, the build is successfully completing when I run it locally on my machine with a max of 8GB of memory.

### PR DESCRIPTION
**Pull request by enriozuni**
Fixes #240 

This PR fixes the failure of the _develop_ branch in the Jenkins server. 

The bug causing the failure was in the POM file where all the rulesets being unpacked in their respective ruleset directories in `src/main/resources` had just the overwrite option in them. This way, when a new ruleset version was released, the CrySL rules were just overwriting the old ones and leading to many "old" rules who were discarded in the new release, to still be around.
This caused many unexpected and strange errors. The fix was to initially delete the whole rulesets, before unpacking the new ones.

Furthermore, the CryptoGuard tests are ignored for now. This is because of the target projects that these tests are using. These projects are not able to compile in the Jenkins server. I will look into this specific issue after this PR is merged. Maybe this is caused by some outdated code in the server's cache.

### CODE REVIEW

**Comment by kruegers** [comment]
Hey @enriozuni ,
Thanks a lot for this PR. I've got two questions, though. 1) Is there a reason you set the surefire version back 2.19.2? 2) are option modification still necessary? So do we need to set the heap size to 16 GB?


For @krinara86, @AnakinSklavenwalker, and @schlichtig: As Enri writes above, this PR sets the CryptoGuard-related test cases on Ignore. I would rather like to wait with merging the PR until we have found a solution concerning the build problems because if we merge it now, we are only masking the fact that our build still does not pass. What do you think about that?

**Comment by enriozuni** [comment]
Hey @kruegers ,
1) There is not a specific reason that I used that surefire version. I saw in maven central that it was the most used one right now, so I thought of going with that. I tested with other versions and they are alright as well.
2) I have tested a couple of times with 12GB and the built failed. With the 16GB was the only time that succeeded.

P.S. I have also some doubts about the VMs in Jenkins. What are their configurations? I saw that we have available 4 different VMs in Jenkins and was wondering if they allow us to configure them up to 16GB of memory.

**Comment by kruegers** [comment]
Hey Enri,

Ok, then please change it back to 2.20.  As far as Jenkins is concerned, we'll leave it at that then. We should perhaps look into test-case sampling, so we don't always need to run the whole test suite. 16 GB is quite the memory demand. The setup on the server should not pose a problem though since the SAST build is running on our own Jenkins server.

**Comment by enriozuni** [comment]
@kruegers I also think test case sampling is a good idea since we have so many test cases right now.

**Comment by kruegers** [comment]
Pinging @krinara86, @schlichtig, and @AnakinSklavenwalker again to get this conversation going.

**Comment by johspaeth** [comment]
Thanks a lot @enriozuni 

If you look into test case sampling, then please set up the pipeline in a way that for every PR into master _all_ test cases are executed. Sampling could still be used on each individual commit though.

**Comment by schlichtig** [comment]
Thanks @enriozuni 

I agree with @kruegers that the CryptoGuard tests should not be ignored.

**Comment by enriozuni** [comment]
> Thanks a lot @enriozuni 
> 
> If you look into test case sampling, then please set up the pipeline in a way that for every PR into master _all_ test cases are executed. Sampling could still be used on each individual commit though. 

Yeah, that's a good idea. Thanks @johspaeth

**Comment by enriozuni** [comment]
> Thanks @enriozuni 
> 
> I agree with @kruegers that the CryptoGuard tests should not be ignored.

I agree as well. Will work to fix them in this PR. Thanks

**Comment by krinara86** [comment]
I am bit skeptical about test code sampling.  How do we decide which tests relate to what code. A code written some place could break some code some other unconnected surprising place. Which is why we have CIs in the first place.  The issue with using "all tests" only for pull requests for master is that bugs are detected really late. Can we have an option to forcibly trigger all tests for individual commits? 

 Question is why is test cases consuming so much resources. Is it because of the Eclipse plugins loading in the background.  Can we consider reusing the same environment for multiple tests.

**Comment by enriozuni** [comment]
@krinara86 I agree with your point. It is not the best practice to do test sampling. I guess I could try and see if I can add the option of running all tests for specific commits.

**Comment by kruegers** [comment]
We are not talking about CogniCrypt here, but CogniCrypt<sub>SAST</sub>. The issues are therefore unrelated to any Eclipse plugin taking resources. <sub>SAST</sub> has always been fairly memory-intensive and the more test cases there are the more analyses need to be run.

There is nothing wrong with running only a subset of test cases per se, we just need to make sure that we run the subset that corresponds to whatever changes have occured since the last build. There is definitely research on the topic like [this](https://ieeexplore.ieee.org/abstract/document/6498459/), [this](https://link.springer.com/article/10.1007/s10664-015-9405-5) or [this](https://www.researchgate.net/publication/279530047_15_Years_of_Software_Regression_Testing_Techniques_--_A_Survey). I was hoping that there'd also be tools that would take care of that for us (e.g., a Jenkins plugin, perhaps), but I don't know. In any case, I do however agree with @johspaeth that we should set up our CI such that the whole test suite is run whenever the master branch is built. To further offset problems with late bug detection, we can also set Jenkins up such that it runs the whole test suite once every two weeks.

**Pull request merged**
