### PR TITLE
Issue 134: Headless tests from CryptoGuard benchmarking tool projects

### LINKED ISSUE #134: Headless test cases for CryptoGuard Crypto-API Benchmark
For their work on CryptoGuard, the authors have come up with a [benchmark](https://github.com/CryptoGuardOSS/cryptoapi-bench/tree/master/src/main/java/org/cryptoapi/bench) to compare against different tools. According to the [paper](https://arxiv.org/pdf/1806.06881.pdf#page=10), CogniCrypt<sub>SAST</sub> currently misses a lot of the misuses specified in the benchmark. 

Go through the benchmark and create test cases from the misuses in there, there are CrySL rules for. For each misuse, there exists no CrySL rule for, file a feature request like [this one](https://github.com/CROSSINGTUD/Crypto-API-Rules/issues/22) here over in the [Crypto API Rules repo](https://github.com/CROSSINGTUD/Crypto-API-Rules/issues/new).

Note: Before creating a particular test case, check whether another one already covers that particular case.

### PR DESCRIPTION
**Pull request by enriozuni**
Closes #134 

This contains Headless tests that were previously covered from CryptoGuard benchmarking tool.

### CODE REVIEW

**Comment by johspaeth** [comment]
@enriozuni 
I only see some of the test cases of CryptoGuard. Are all implemented? On Monday, we discussed that we would like to have an automatic way to detect if a method should be flagged vulnerable by CryptoAnalysis (for instance when the class name starts with Broken...). Did you find any semantics/specification in the benchmark that we could rely on for this automatic inference of the specification of the tests.

I really would like to prevent manually specification of all issues. (At least not as long we debug anything).

**Comment by enriozuni** [comment]
> @enriozuni
> I only see some of the test cases of CryptoGuard. Are all implemented? On Monday, we discussed that we would like to have an automatic way to detect if a method should be flagged vulnerable by CryptoAnalysis (for instance when the class name starts with Broken...). Did you find any semantics/specification in the benchmark that we could rely on for this automatic inference of the specification of the tests.
> 
> I really would like to prevent manually specification of all issues. (At least not as long we debug anything).

@johspaeth sorry for the confusion. I am still working on the part of automating the process. I had a meeting with @kruegers yesterday and wanted to show him my findings on the headless tests from the CryptoGuard, that is why I have only included the manually-specified headless tests. Also, some tests are missing because they are either similar to the the ones already included, or the expected misuses are not caught in them by the analysis. About the last one, I will prepare a short presentation on our weekly meeting this Monday and show what are the misuses that are not caught.

**Comment by johspaeth** [comment]
Thanks @enriozuni 

Before I merge, I want to know the effect on the test case execution time. How much longer does the testing time execution get when we also run these test cases in addition to the test prior to the pull request? Could you do a quick diff on your machine before and after and report the numbers?

I just want to prevent us from having too many unnecessary test running on each commit.

**Comment by enriozuni** [comment]
> Thanks @enriozuni
> 
> Before I merge, I want to know the effect on the test case execution time. How much longer does the testing time execution get when we also run these test cases in addition to the test prior to the pull request? Could you do a quick diff on your machine before and after and report the numbers?
> 
> I just want to prevent us from having too many unnecessary test running on each commit.

@johspaeth The CryptGuard tests add an additional of 68 seconds to the overall testing execution time.

**Pull request merged**
